__author__ = "Manuel Meitinger"
__email__ = "manuel@meitinger.at"
__license__ = "BSD"
__summary__ = "Fork of Jeremy Lainé's aioquic with adjustments for mitmproxy."
__title__ = "aioquic_mitmproxy"
__uri__ = "https://github.com/meitinger/aioquic_mitmproxy"
__version__ = "0.9.20"
